[package]
name = "rust-stm32-playground"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "hello_led_btn_isr",
    "hello_spi",
    "hello_led",
    "hello_srf05",
    "hello_tracker",
    "hello_analog_potentiometer"
]
